jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - python/install-packages:
          pkg-manager: poetry
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - home/circleci/.cache/pypoetry/virtualenvs
      - run:
          command: |
            poetry run pytest
          name: Test it
orbs:
  python: circleci/python@1.3.2
version: 2.1
workflows:
  main:
    jobs:
      - build
